### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by asvyshar** [localjo/react-tater#1]
Hi. What do you think about Typescript support for this lib?

**Comment by localjo** [comment]
I like the idea. I don't know what it takes to add TypeScript support, so it will take me a few days to figure it out. In the meantime, I think you can still use it in a TypeScript project with;

```
// @ts-ignore
import Tater from 'react-tater';
```

If you know what it takes to add TypeScript support, or want to open a PR to do that, it's more than welcome. Thanks!

**Comment by localjo** [comment]
Hi @asvyshar, thanks to @moltar TypeScript support is available in version 2.1.1. Let me know if you have any problems with it. Thanks!
